FROM python:3.11-slim
WORKDIR /app
COPY requirements_gateway.txt .
RUN apt-get update && apt-get install -y \
libglib2.0-0 \
libxext6 \
&& rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements_gateway.txt
COPY . .
# We expose 8000 as the main entry point for the user
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]